# Generated by Django 6.0.5 on 2026-05-23 22:45

import cultivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cultivo')),
                ('agricultor', models.CharField(max_length=100, verbose_name='Nombre del Vecino/Agricultor')),
                ('zona', models.CharField(choices=[('N', 'Zona Norte (Hortalizas)'), ('S', 'Zona Sur (Frutales)'), ('E', 'Zona Este (Legumbres)'), ('O', 'Zona Oeste (Aromáticas)')], max_length=1, verbose_name='Zona del Huerto')),
                ('cantidad_sembrada', models.IntegerField(validators=[cultivos.models.validar_cantidad], verbose_name='Cantidad de Semillas/Plantas')),
                ('fecha_siembra', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
